---
kind: 'pipeline'
type: 'docker'
name: 'documentation'
steps:
  - name: 'build'
    image: 'python:3'
    commands:
      - '.drone/documentation-build.sh'
  - name: 'push'
    image: 'alpine'
    commands:
      - 'apk add git openssh'
      - '.drone/documentation-push.sh'
    environment:
      GH_DEPLOY_KEY:
        from_secret: 'GH_DEPLOY_KEY'
trigger:
  branch:
    - 'master'
  event:
    - 'push'
---
kind: signature
hmac: 530cd3794afb262f6738f630ed4ebce2b6769f190794b23d2cc7271698e944aa

...
